In [132]:
# Complete Numpy practice help of Udemy online courses.

In [ ]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

In [2]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [3]:
#print dimensions

a.ndim

1

In [4]:
#shape

a.shape

(4,)

In [5]:
len(a)

4

In [6]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b.shape


(2, 3)

In [9]:
len(b) #returns the size of the first dimention

2

In [10]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [13]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [18]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [20]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([0.21154005, 0.30363323, 0.36209389, 0.49253486])

In [26]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 1.43834532, -0.60761082, -1.34913912,  1.11723322])

# DATA TYPES

In [58]:
x=np.array([1,2,3],np.int16) #16 bit data type declaration

In [60]:
print(x)

print(type(x))

[1 2 3]
<type 'numpy.ndarray'>


In [61]:
print(x[-1]) # last element of array

3


In [63]:
x=np.array([[1,2,3],[2,3,4]],np.int16) #16 bit data type

In [64]:
print(x[0,0])

1


In [65]:
print(x[:,0]) #first coulmns

[1 2]


In [67]:
print(x[:,2]) #third coulmns

[3 4]


In [68]:
print(x[0,:]) #first row

[1 2 3]


In [69]:
print(x[1,:]) #Second Row row

[2 3 4]


In [70]:
x=np.array([[[1,2,3],[2,3,4]],[[4,6,8],[-7,5,4]]],np.int16) #3 dimensional array

In [71]:
print(x[0,0,0]) # first hipe,first row, first coulmn, 

1


In [73]:
print(x[1,0,1]) # second hipe, first row, second coulmns

6


In [86]:
print(x.dtype)       
print(x.size) #refers to number of element in the array
print(x.ndim)
print(x.shape)
print(x.nbytes) #correct size in bytes

uint8
25
2
(5, 5)
25


In [89]:
x.max()
x.min()

1

In [78]:
print(x.T) # transpose of multi dimensional array

[[[ 1  4]
  [ 2 -7]]

 [[ 2  6]
  [ 3  5]]

 [[ 3  8]
  [ 4  4]]]


In [79]:
print(np.e)
print(np.pi)
print(np.euler_gamma)

2.71828182846
3.14159265359
0.577215664902


In [22]:
a = np.arange(10)

a.dtype

dtype('int64')

In [23]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [25]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [80]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


# Matrics Creation Routines

In [81]:
x=np.tri(3,3,k=-1,dtype=np.uint16)
print(x)

[[0 0 0]
 [1 0 0]
 [1 1 0]]


In [83]:
x=np.tri(5,5,k=0,dtype=np.uint16) #k=-1/0/1
print(x)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


In [84]:
x=np.tri(3,3,k=1,dtype=np.uint16) #diagonal shifted by one position
print(x)

[[1 1 0]
 [1 1 1]
 [1 1 1]]


In [85]:
x=np.ones((5,5),dtype=np.uint8)
y=np.tril(x,k=-1) #lower triangular element means by k=-1
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


# Indexing 

In [28]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [30]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [31]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

# Slicing

In [32]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [34]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [35]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Operation


In [123]:
x=np.array([1,0,1,0],np.uint8)
y=np.array([0,0,1,1],np.uint8)
print(np.bitwise_and(x,y))
print(np.bitwise_or(x,y))
print(np.bitwise_xor(x,y))
print(np.bitwise_not(x,y))

[0 0 1 0]
[1 0 1 1]
[1 0 0 1]
[254 255 254 255]


In [36]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [37]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
b = np.ones(4) + 1

a - b

array([-1.,  0.,  1.,  2.])

In [39]:
a * b

array([2., 4., 6., 8.])

In [40]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

print(c * c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [41]:
a = np.array([1, 2, 3, 4]) #comparison
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [42]:
a > b

array([False, False,  True, False])

In [43]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [44]:
np.array_equal(a, c)

True

In [45]:
a = np.array([1, 1, 0, 0], dtype=bool)  #Logical Operation
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [46]:
np.logical_and(a, b)

array([ True, False, False, False])

In [47]:
a = np.arange(5) #transcendental function

np.sin(a) 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [48]:
np.log(a)

/home/saiful/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

# statistical operation

In [124]:
x = np.array([1, 2, 3, 1])   
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [127]:
z=np.random.randint(low=0,high=10,size=10)

In [129]:
print(np.histogram(z))  #here first array means frequency and second means bins

(array([1, 3, 0, 0, 1, 1, 1, 0, 2, 1]), array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ]))


In [130]:
print(np.mean(z))
print(np.average(z))
print(np.std(z))
print(np.var(z))

4.3
4.3
3.2264531609803355
10.41


In [50]:
np.median(x)

1.5

In [51]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [55]:
x.std()          # full population standard dev.

0.82915619758885

# Sorting

In [53]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [54]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [56]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [57]:
a[j]

array([1, 2, 3, 4])

# Array Manipulation Routines

In [90]:
x=np.arange(6)
print(x)

[0 1 2 3 4 5]


In [91]:
y=x.reshape((3,2)) #it is create two dimensional matrics out of one dimensional array
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [92]:
x=np.array([[0,1,2],[3,4,5]], dtype=np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [94]:
y=np.reshape(x,6)
print(y)
print(x)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [95]:
y=np.ravel(x) #its achieve the same functionality of reshape(x,6)
print(y)

[0 1 2 3 4 5]


In [96]:
y=x.flatten() #default row wise
print(y)

[0 1 2 3 4 5]


In [97]:
y=x.flatten('C') #it also row wise
print(y)

[0 1 2 3 4 5]


In [98]:
y=x.flatten('F')  #cloumn wise
print(y)

[0 3 1 4 2 5]


In [99]:
x=np.array([1,2,3],dtype=np.uint8) #dtype save the memory used...thats why declare is good practice
y=np.array([4,5,6],dtype=np.uint8)
print(x.dtype)
print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [100]:
z=np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [101]:
z=np.stack((x,y),axis=0)
print(z)

[[1 2 3]
 [4 5 6]]


In [102]:
z=np.stack((x,y),axis=1) #axis may 0/1/-1

print(z)


[[1 4]
 [2 5]
 [3 6]]


In [103]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [104]:
z=np.dstack((x,y)) 

print(z)
print(z.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [105]:
z=np.hstack((x,y)) 

print(z)


[1 2 3 4 5 6]


In [106]:
z=np.vstack((x,y)) 

print(z)
print(z.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [107]:
x=np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [108]:
a,b,c=np.split(x,3)
print(a,b,c)

(array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]))


In [109]:
x=np.random.rand(4,4,4)
print(x)

[[[0.27000776 0.40513216 0.13518439 0.98661078]
  [0.43864178 0.04203845 0.40285847 0.86981457]
  [0.68026584 0.29516615 0.93003994 0.98486382]
  [0.75135537 0.54642852 0.62970214 0.45942012]]

 [[0.87380764 0.75393147 0.97768604 0.78003018]
  [0.91333165 0.0707714  0.25845271 0.23759691]
  [0.15520527 0.36581221 0.0762618  0.05247769]
  [0.23836592 0.14408915 0.4113828  0.63927248]]

 [[0.36474311 0.98957429 0.23022389 0.90786516]
  [0.7195986  0.43774496 0.90872103 0.56848873]
  [0.92215134 0.99913655 0.36244732 0.5546681 ]
  [0.52211179 0.66574159 0.74704311 0.77296433]]

 [[0.3009633  0.60261462 0.04944062 0.48227326]
  [0.23453586 0.92860985 0.33701065 0.18685935]
  [0.75743228 0.58370164 0.55605105 0.35354306]
  [0.2749035  0.01620681 0.0338055  0.6982352 ]]]


In [110]:
y,z=np.split(x,2)
print(y,z)

(array([[[0.27000776, 0.40513216, 0.13518439, 0.98661078],
        [0.43864178, 0.04203845, 0.40285847, 0.86981457],
        [0.68026584, 0.29516615, 0.93003994, 0.98486382],
        [0.75135537, 0.54642852, 0.62970214, 0.45942012]],

       [[0.87380764, 0.75393147, 0.97768604, 0.78003018],
        [0.91333165, 0.0707714 , 0.25845271, 0.23759691],
        [0.15520527, 0.36581221, 0.0762618 , 0.05247769],
        [0.23836592, 0.14408915, 0.4113828 , 0.63927248]]]), array([[[0.36474311, 0.98957429, 0.23022389, 0.90786516],
        [0.7195986 , 0.43774496, 0.90872103, 0.56848873],
        [0.92215134, 0.99913655, 0.36244732, 0.5546681 ],
        [0.52211179, 0.66574159, 0.74704311, 0.77296433]],

       [[0.3009633 , 0.60261462, 0.04944062, 0.48227326],
        [0.23453586, 0.92860985, 0.33701065, 0.18685935],
        [0.75743228, 0.58370164, 0.55605105, 0.35354306],
        [0.2749035 , 0.01620681, 0.0338055 , 0.6982352 ]]]))


In [111]:
y,z=np.dsplit(x,2) #split accordingto the dept
print(y,z)

(array([[[0.27000776, 0.40513216],
        [0.43864178, 0.04203845],
        [0.68026584, 0.29516615],
        [0.75135537, 0.54642852]],

       [[0.87380764, 0.75393147],
        [0.91333165, 0.0707714 ],
        [0.15520527, 0.36581221],
        [0.23836592, 0.14408915]],

       [[0.36474311, 0.98957429],
        [0.7195986 , 0.43774496],
        [0.92215134, 0.99913655],
        [0.52211179, 0.66574159]],

       [[0.3009633 , 0.60261462],
        [0.23453586, 0.92860985],
        [0.75743228, 0.58370164],
        [0.2749035 , 0.01620681]]]), array([[[0.13518439, 0.98661078],
        [0.40285847, 0.86981457],
        [0.93003994, 0.98486382],
        [0.62970214, 0.45942012]],

       [[0.97768604, 0.78003018],
        [0.25845271, 0.23759691],
        [0.0762618 , 0.05247769],
        [0.4113828 , 0.63927248]],

       [[0.23022389, 0.90786516],
        [0.90872103, 0.56848873],
        [0.36244732, 0.5546681 ],
        [0.74704311, 0.77296433]],

       [[0.04944062, 0.48227326]

In [112]:
y,z=np.hsplit(x,2)
print(y,z)

(array([[[0.27000776, 0.40513216, 0.13518439, 0.98661078],
        [0.43864178, 0.04203845, 0.40285847, 0.86981457]],

       [[0.87380764, 0.75393147, 0.97768604, 0.78003018],
        [0.91333165, 0.0707714 , 0.25845271, 0.23759691]],

       [[0.36474311, 0.98957429, 0.23022389, 0.90786516],
        [0.7195986 , 0.43774496, 0.90872103, 0.56848873]],

       [[0.3009633 , 0.60261462, 0.04944062, 0.48227326],
        [0.23453586, 0.92860985, 0.33701065, 0.18685935]]]), array([[[0.68026584, 0.29516615, 0.93003994, 0.98486382],
        [0.75135537, 0.54642852, 0.62970214, 0.45942012]],

       [[0.15520527, 0.36581221, 0.0762618 , 0.05247769],
        [0.23836592, 0.14408915, 0.4113828 , 0.63927248]],

       [[0.92215134, 0.99913655, 0.36244732, 0.5546681 ],
        [0.52211179, 0.66574159, 0.74704311, 0.77296433]],

       [[0.75743228, 0.58370164, 0.55605105, 0.35354306],
        [0.2749035 , 0.01620681, 0.0338055 , 0.6982352 ]]]))


In [113]:
y,z=np.vsplit(x,2)
print(y,z)

(array([[[0.27000776, 0.40513216, 0.13518439, 0.98661078],
        [0.43864178, 0.04203845, 0.40285847, 0.86981457],
        [0.68026584, 0.29516615, 0.93003994, 0.98486382],
        [0.75135537, 0.54642852, 0.62970214, 0.45942012]],

       [[0.87380764, 0.75393147, 0.97768604, 0.78003018],
        [0.91333165, 0.0707714 , 0.25845271, 0.23759691],
        [0.15520527, 0.36581221, 0.0762618 , 0.05247769],
        [0.23836592, 0.14408915, 0.4113828 , 0.63927248]]]), array([[[0.36474311, 0.98957429, 0.23022389, 0.90786516],
        [0.7195986 , 0.43774496, 0.90872103, 0.56848873],
        [0.92215134, 0.99913655, 0.36244732, 0.5546681 ],
        [0.52211179, 0.66574159, 0.74704311, 0.77296433]],

       [[0.3009633 , 0.60261462, 0.04944062, 0.48227326],
        [0.23453586, 0.92860985, 0.33701065, 0.18685935],
        [0.75743228, 0.58370164, 0.55605105, 0.35354306],
        [0.2749035 , 0.01620681, 0.0338055 , 0.6982352 ]]]))


In [114]:
x=np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [115]:
y=np.flip(x,axis=0)

In [116]:
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [117]:
y=np.flip(x,axis=1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [118]:
y=np.flip(x)
print(y)

[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [119]:
y=np.fliplr(x)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [120]:
y=np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [121]:
y=np.roll(x,8) #its just exchange the last 8 element
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [122]:
y=np.rot90(x) #changes  row into columns and rotated the enter matrix anti clock wise
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
